// Copyright 2026 FINOS
// SPDX-License-Identifier: Apache-2.0
//
// Checks that every value in the Morphir.IR.SDK package specification of
// finos/morphir-elm has an export of the same name. The names below are the
// `vSpec` entries of each `Morphir.IR.SDK.<Module>` file, in file order.
import { describe, expect, test } from "bun:test";
import * as sdk from "./index.ts";

const SPEC: Readonly<Record<string, readonly string[]>> = {
	Basics: [
		"add",
		"subtract",
		"multiply",
		"divide",
		"integerDivide",
		"power",
		"toFloat",
		"round",
		"floor",
		"ceiling",
		"truncate",
		"modBy",
		"remainderBy",
		"negate",
		"abs",
		"clamp",
		"isNaN",
		"isInfinite",
		"sqrt",
		"logBase",
		"e",
		"pi",
		"cos",
		"sin",
		"tan",
		"acos",
		"asin",
		"atan",
		"atan2",
		"degrees",
		"radians",
		"turns",
		"toPolar",
		"fromPolar",
		"equal",
		"notEqual",
		"lessThan",
		"greaterThan",
		"lessThanOrEqual",
		"greaterThanOrEqual",
		"max",
		"min",
		"compare",
		"not",
		"and",
		"or",
		"xor",
		"append",
		"identity",
		"always",
		"composeLeft",
		"composeRight",
		"never",
	],
	Char: [
		"isUpper",
		"isLower",
		"isAlpha",
		"isAlphaNum",
		"isDigit",
		"isOctDigit",
		"isHexDigit",
		"toUpper",
		"toLower",
		"toLocaleUpper",
		"toLocaleLower",
		"toCode",
		"fromCode",
	],
	String: [
		"isEmpty",
		"length",
		"reverse",
		"repeat",
		"replace",
		"append",
		"concat",
		"split",
		"join",
		"words",
		"lines",
		"slice",
		"left",
		"right",
		"dropLeft",
		"dropRight",
		"contains",
		"startsWith",
		"endsWith",
		"indexes",
		"indices",
		"toInt",
		"fromInt",
		"toFloat",
		"fromFloat",
		"fromChar",
		"cons",
		"uncons",
		"toList",
		"fromList",
		"toUpper",
		"toLower",
		"pad",
		"padLeft",
		"padRight",
		"trim",
		"trimLeft",
		"trimRight",
		"map",
		"filter",
		"foldl",
		"foldr",
		"any",
		"all",
	],
	List: [
		"singleton",
		"repeat",
		"range",
		"cons",
		"map",
		"indexedMap",
		"foldl",
		"foldr",
		"filter",
		"filterMap",
		"length",
		"reverse",
		"member",
		"all",
		"any",
		"maximum",
		"minimum",
		"sum",
		"product",
		"append",
		"concat",
		"concatMap",
		"intersperse",
		"map2",
		"map3",
		"map4",
		"map5",
		"sort",
		"sortBy",
		"sortWith",
		"isEmpty",
		"head",
		"tail",
		"take",
		"drop",
		"partition",
		"unzip",
		"innerJoin",
		"leftJoin",
	],
	Dict: [
		"empty",
		"singleton",
		"insert",
		"update",
		"remove",
		"isEmpty",
		"member",
		"get",
		"size",
		"keys",
		"values",
		"toList",
		"fromList",
		"map",
		"foldl",
		"foldr",
		"filter",
		"partition",
		"union",
		"intersect",
		"diff",
		"merge",
	],
	Set: [
		"empty",
		"singleton",
		"insert",
		"remove",
		"isEmpty",
		"member",
		"size",
		"toList",
		"fromList",
		"map",
		"foldl",
		"foldr",
		"filter",
		"partition",
		"union",
		"intersect",
		"diff",
	],
	Maybe: ["andThen", "map", "map2", "map3", "map4", "map5", "withDefault", "hasValue"],
	Result: ["andThen", "map", "map2", "map3", "map4", "map5", "withDefault", "toMaybe", "fromMaybe", "mapError"],
	Tuple: ["pair", "first", "second", "mapFirst", "mapSecond", "mapBoth"],
	Decimal: [
		"fromInt",
		"fromFloat",
		"fromString",
		"hundred",
		"thousand",
		"million",
		"tenth",
		"hundredth",
		"thousandth",
		"millionth",
		"bps",
		"toString",
		"toFloat",
		"add",
		"sub",
		"negate",
		"mul",
		"div",
		"divWithDefault",
		"truncate",
		"round",
		"gt",
		"gte",
		"eq",
		"neq",
		"lt",
		"lte",
		"compare",
		"abs",
		"shiftDecimalLeft",
		"shiftDecimalRight",
		"zero",
		"one",
		"minusOne",
	],
	Int: ["fromInt8", "toInt8", "fromInt16", "toInt16", "fromInt32", "toInt32", "fromInt64", "toInt64"],
	Number: [
		"fromInt",
		"equal",
		"notEqual",
		"lessThan",
		"lessThanOrEqual",
		"greaterThan",
		"greaterThanOrEqual",
		"add",
		"subtract",
		"multiply",
		"divide",
		"abs",
		"negate",
		"reciprocal",
		"coerceToDecimal",
		"toDecimal",
		"toFractionalString",
		"simplify",
		"isSimplified",
		"zero",
		"one",
	],
	LocalDate: [
		"fromCalendarDate",
		"toISOString",
		"fromISO",
		"fromOrdinalDate",
		"fromParts",
		"day",
		"dayOfWeek",
		"diffInDays",
		"diffInWeeks",
		"diffInMonths",
		"diffInYears",
		"addDays",
		"addWeeks",
		"addMonths",
		"addYears",
		"isWeekend",
		"isWeekday",
		"month",
		"monthNumber",
		"monthToInt",
		"year",
	],
	LocalTime: ["fromISO", "fromMilliseconds", "diffInSeconds", "diffInMinutes", "diffInHours", "addSeconds", "addMinutes", "addHours"],
	Instant: [],
	UUID: [
		"parse",
		"fromString",
		"forName",
		"toString",
		"version",
		"compare",
		"nilString",
		"isNilString",
		"dnsNamespace",
		"urlNamespace",
		"oidNamespace",
		"x500Namespace",
	],
	Regex: ["fromString", "fromStringWith", "never", "contains", "split", "find", "replace", "splitAtMost", "findAtMost", "replaceAtMost"],
	Aggregate: [
		"count",
		"sumOf",
		"averageOf",
		"minimumOf",
		"maximumOf",
		"weightedAverageOf",
		"byKey",
		"withFilter",
		"aggregateMap",
		"aggregateMap2",
		"aggregateMap3",
		"aggregateMap4",
		"groupBy",
		"aggregate",
	],
	Rule: ["chain", "any", "is", "anyOf", "noneOf"],
	Key: ["noKey", "key0", "key2", "key3", "key4", "key5", "key6", "key7", "key8", "key9", "key10", "key11", "key12", "key13", "key14", "key15", "key16"],
	StatefulApp: [],
	ResultList: ["fromList", "filter", "filterOrFail", "map", "mapOrFail", "errors", "successes", "partition", "keepAllErrors", "keepFirstError"],
};

describe("Morphir.IR.SDK specification coverage", () => {
	test("every specified module is a namespace on the root entry", () => {
		expect(Object.keys(sdk).sort()).toEqual(Object.keys(SPEC).sort());
	});

	for (const [moduleName, names] of Object.entries(SPEC)) {
		test(`${moduleName} exports every specified value`, () => {
			const namespace = (sdk as Record<string, Record<string, unknown>>)[moduleName] ?? {};
			const missing = names.filter((name) => namespace[name] === undefined);
			expect(missing).toEqual([]);
		});
	}
});
