// Copyright 2026 FINOS
// SPDX-License-Identifier: Apache-2.0
import { describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, symlinkSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { referenceResolutionTestee } from "../src/package/reference.ts";
import { loadResolutionKit, loadResolutionKitFromFiles } from "../src/package/resolution/corpus.ts";
import { packageExitCode, runResolutionKit } from "../src/package/run.ts";
import { resolutionFiles, writeResolutionPackage } from "./package-resolution-fixture.ts";

// biome-ignore lint/suspicious/noExplicitAny: mutation-focused malformed JSON fixtures intentionally have varying shapes.
function replaceJson(files: Map<string, Uint8Array>, name: string, update: (value: any) => void): void {
	const value = JSON.parse(new TextDecoder().decode(files.get(name)));
	update(value);
	files.set(name, new TextEncoder().encode(JSON.stringify(value)));
}

describe("resolution corpus", () => {
	test("loads fixed cases and consumes every schema and expectation byte", () => {
		const kit = loadResolutionKitFromFiles(resolutionFiles());
		expect(kit.errors).toEqual([]);
		expect(kit.cases).toHaveLength(2);
		expect(kit.contentHash).toMatch(/^sha256-[a-f0-9]{64}$/);

		for (const changed of ["mck/resolution-cases.json", "mck/fixtures/resolution/basic.json", "schemas/resolution-result.schema.json"]) {
			const files = resolutionFiles();
			files.set(changed, Buffer.concat([Buffer.from(files.get(changed) as Uint8Array), Buffer.from("\n")]));
			expect(loadResolutionKitFromFiles(files).contentHash).not.toBe(kit.contentHash);
		}
	});

	test("fixed expectations are compared, never generated by the resolver", async () => {
		const files = resolutionFiles();
		replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
			fixture.cases[1].expected.graph.nodes[0].contentDigest = `sha256:${"1".repeat(64)}`;
		});
		const report = await runResolutionKit(loadResolutionKitFromFiles(files), referenceResolutionTestee());
		expect(report.records[1]).toMatchObject({ caseId: "resolution.initial.root", result: "fail" });
		expect(packageExitCode(report)).toBe(1);
	});

	test("malformed raw input remains a legitimate domain case", () => {
		const files = resolutionFiles();
		replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
			fixture.cases = [
				{
					id: "resolution.invalid.raw",
					family: "profile-boundaries",
					description: "Raw syntax failure",
					input: "{",
					expected: { ok: false, diagnostic: { code: "invalid-input", violations: [{ pointer: "", rule: "malformed-json" }] } },
				},
			];
		});
		const kit = loadResolutionKitFromFiles(files);
		expect(kit.errors).toEqual([]);
		expect(kit.cases[0]?.request.input).toBe("{");
	});

	test.each([
		[
			"malformed fixture envelope",
			(files: Map<string, Uint8Array>) => replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => (fixture.extra = true)),
		],
		[
			"duplicate ids",
			(files: Map<string, Uint8Array>) =>
				replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
					fixture.cases.push(structuredClone(fixture.cases[0]));
				}),
		],
		["path escape", (files: Map<string, Uint8Array>) => replaceJson(files, "mck/resolution-cases.json", (index) => (index.fixtures = ["../outside.json"]))],
		[
			"unknown operation",
			(files: Map<string, Uint8Array>) => replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => (fixture.cases[0].operation = "other")),
		],
		[
			"malformed expected graph",
			(files: Map<string, Uint8Array>) => replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => delete fixture.cases[1].expected.graph.nodes),
		],
		[
			"duplicate expected graph identity",
			(files: Map<string, Uint8Array>) =>
				replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) =>
					fixture.cases[1].expected.graph.nodes.push(structuredClone(fixture.cases[1].expected.graph.nodes[0])),
				),
		],
		[
			"dangling expected graph binding",
			(files: Map<string, Uint8Array>) =>
				replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
					fixture.cases[1].expected.graph.nodes[0].bindings.push({
						irPackageName: "example/missing",
						target: { packagePath: "example.com/lib/missing", version: "1.0.0" },
					});
				}),
		],
		[
			"expected graph binding name mismatches its target node",
			(files: Map<string, Uint8Array>) =>
				replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
					const root = fixture.cases[1].expected.graph.nodes[0];
					const childRelease = { packagePath: "example.com/lib/child", version: "1.0.0" };
					root.bindings.push({ irPackageName: "example/wrong", target: childRelease });
					fixture.cases[1].expected.graph.nodes.push({ ...structuredClone(root), release: childRelease, irPackageName: "example/child", bindings: [] });
				}),
		],
		["malformed schema", (files: Map<string, Uint8Array>) => files.set("schemas/resolution-result.schema.json", new TextEncoder().encode('{"type":"wat"}'))],
	] as const)("reports %s as a kit error", (_name, mutate) => {
		const files = resolutionFiles();
		mutate(files);
		const kit = loadResolutionKitFromFiles(files);
		expect(kit.errors.length).toBeGreaterThan(0);
		expect(kit.cases).toEqual([]);
	});

	test("validates witness topology while allowing a shared sibling release", () => {
		const files = resolutionFiles();
		replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
			fixture.cases[0].expected = {
				ok: false,
				diagnostic: {
					code: "unsupported-capability",
					requiredCapabilities: ["graph-aware-coexistence"],
					changedPins: [],
					witness: {
						nodes: [
							{
								occurrence: [],
								release: { packagePath: "example.com/app/root", version: "1.0.0" },
								bindings: [
									{ irPackageName: "example/left", targetOccurrence: ["example/left"] },
									{ irPackageName: "example/right", targetOccurrence: ["example/right"] },
								],
							},
							{
								occurrence: ["example/left"],
								release: { packagePath: "example.com/lib/shared", version: "1.0.0" },
								bindings: [],
							},
							{
								occurrence: ["example/right"],
								release: { packagePath: "example.com/lib/shared", version: "1.0.0" },
								bindings: [],
							},
						],
					},
				},
			};
		});
		expect(loadResolutionKitFromFiles(files).errors).toEqual([]);

		replaceJson(files, "mck/fixtures/resolution/basic.json", (fixture) => {
			const nodes = fixture.cases[0].expected.diagnostic.witness.nodes;
			nodes.push(structuredClone(nodes[1]));
		});
		const invalid = loadResolutionKitFromFiles(files);
		expect(invalid.errors.length).toBeGreaterThan(0);
		expect(invalid.cases).toEqual([]);
	});

	test("rejects a dynamically selected fixture symlink escaping the kit", () => {
		const directory = mkdtempSync(path.join(os.tmpdir(), "mck-resolution-confine-"));
		const outside = mkdtempSync(path.join(os.tmpdir(), "mck-resolution-outside-"));
		try {
			const kitDirectory = writeResolutionPackage(directory);
			const fixture = path.join(kitDirectory, "fixtures/resolution/basic.json");
			rmSync(fixture);
			writeResolutionPackage(outside);
			symlinkSync(path.join(outside, "mck/fixtures/resolution/basic.json"), fixture);
			const kit = loadResolutionKit(kitDirectory);
			expect(kit.errors.join(" ")).toContain("confined");
		} finally {
			rmSync(directory, { recursive: true, force: true });
			rmSync(outside, { recursive: true, force: true });
		}
	});

	test("missing required operation or profile cannot pass", async () => {
		for (const capabilities of [
			{ operations: [] as const, profiles: ["flat-library"] as const },
			{ operations: ["resolve-library"] as const, profiles: [] as const },
		]) {
			const reference = referenceResolutionTestee();
			const report = await runResolutionKit(loadResolutionKitFromFiles(resolutionFiles()), {
				...reference,
				capabilities: async () => ({ ...(await reference.capabilities()), ...capabilities }),
			});
			expect(packageExitCode(report)).toBe(1);
			expect(report.records.some((record) => record.result === "pass")).toBe(false);
		}
	});

	test("one canonical projection compares reordered success nodes and bindings", async () => {
		const kit = loadResolutionKitFromFiles(resolutionFiles());
		const base = kit.cases.find((candidate) => candidate.expected.ok);
		if (!base?.expected.ok) throw new Error("fixture has no success case");
		const firstNode = base.expected.graph.nodes[0];
		if (!firstNode) throw new Error("fixture success graph has no root node");
		const root = {
			...firstNode,
			bindings: [{ irPackageName: "example/child", target: { packagePath: "example.com/lib/child", version: "1.0.0" } }],
		};
		const child = { ...firstNode, release: { packagePath: "example.com/lib/child", version: "1.0.0" }, irPackageName: "example/child" };
		const entry = { ...base, expected: { ok: true as const, graph: { ...base.expected.graph, nodes: [root, child] } } };
		const reference = referenceResolutionTestee();
		const report = await runResolutionKit(
			{ ...kit, cases: [entry] },
			{
				...reference,
				execute: async (request) => {
					void request;
					return { ok: true, graph: { ...entry.expected.graph, nodes: [...entry.expected.graph.nodes].reverse() } };
				},
			},
		);
		expect(report.records[0]?.result).toBe("pass");
	});

	test("one canonical projection compares reordered diagnostic evidence", async () => {
		const kit = loadResolutionKitFromFiles(resolutionFiles());
		const base = kit.cases.find((candidate) => !candidate.expected.ok);
		if (!base || base.expected.ok || !("violations" in base.expected.diagnostic)) throw new Error("fixture has no violation case");
		const violations = [...base.expected.diagnostic.violations, { pointer: "/z", rule: "unknown-field" as const }];
		const entry = { ...base, expected: { ok: false as const, diagnostic: { code: "invalid-input" as const, violations } } };
		const reference = referenceResolutionTestee();
		const report = await runResolutionKit(
			{ ...kit, cases: [entry] },
			{
				...reference,
				execute: async (request) => {
					void request;
					return { ok: false, diagnostic: { ...entry.expected.diagnostic, violations: [...violations].reverse() } };
				},
			},
		);
		expect(report.records[0]?.result).toBe("pass");
	});
});
