// Copyright 2026 FINOS
// SPDX-License-Identifier: Apache-2.0
//
// The vendored kit: a byte-for-byte copy of finos/morphir's spec/ir/mck plus
// every repository file a `text` fence names, stored under packages/mck/kit/
// by repository-relative path, pinned by kit.lock.json. `sync` replaces the
// copy wholesale; `status` proves the copy still matches the lock.
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { contentHash } from "./hash.ts";
import { loadKit } from "./load.ts";
import { KIT_PATH, resolveTextFence } from "./source.ts";

export interface KitLock {
	readonly repository: string;
	readonly path: string;
	readonly commit: string;
	readonly contentHash: string;
	readonly syncedAt: string;
}

const REPOSITORY = "https://github.com/finos/morphir";
const LOCK = "kit.lock.json";
const EMBEDDED = "embedded.ts";

function git(cwd: string, ...args: string[]): string {
	return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

function walkBytes(directory: string, prefix: string, out: Map<string, Uint8Array>): void {
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const absolute = path.join(directory, entry.name);
		const key = `${prefix}/${entry.name}`;
		if (entry.isDirectory()) walkBytes(absolute, key, out);
		else if (entry.isFile() && entry.name !== EMBEDDED) out.set(key, new Uint8Array(readFileSync(absolute)));
	}
}

export async function collectSnapshot(repositoryRoot: string): Promise<Map<string, Uint8Array>> {
	const kitDirectory = path.join(repositoryRoot, ...KIT_PATH.split("/"));
	const files = new Map<string, Uint8Array>();
	walkBytes(kitDirectory, KIT_PATH, files);
	const kit = await loadKit(kitDirectory, repositoryRoot);
	if (kit.errors.length > 0) throw new Error(`kit at ${kitDirectory} has ${kit.errors.length} error(s); fix them before syncing`);
	for (const c of kit.cases) {
		for (const f of c.fences) {
			if (f.info.language !== "text") continue;
			const r = resolveTextFence(kit, f);
			if (!r.ok) throw new Error(`${c.id}: ${r.message}`);
			files.set(r.path, new TextEncoder().encode(r.content));
		}
	}
	return files;
}

function snapshotOf(packageRoot: string): Map<string, Uint8Array> {
	const files = new Map<string, Uint8Array>();
	const kitDirectory = path.join(packageRoot, "kit");
	for (const top of readdirSync(kitDirectory, { withFileTypes: true })) {
		if (top.isDirectory()) walkBytes(path.join(kitDirectory, top.name), top.name, files);
	}
	return files;
}

export function readLock(packageRoot: string): KitLock {
	return JSON.parse(readFileSync(path.join(packageRoot, LOCK), "utf8")) as KitLock;
}

export function writeLock(packageRoot: string, lock: KitLock): void {
	writeFileSync(path.join(packageRoot, LOCK), `${JSON.stringify(lock, null, "\t")}\n`);
}

// The embedded copy is a generated module of string literals: no import
// attributes, nothing for the bundler or tsc to special-case, and the
// compiled binaries carry it without any file-embedding support.
function embeddedModule(files: ReadonlyMap<string, Uint8Array>, commit: string): string {
	const dec = new TextDecoder();
	const entries = [...files.keys()].sort().map((p) => `\t[${JSON.stringify(p)}, ${JSON.stringify(dec.decode(files.get(p) as Uint8Array))}],`);
	return [
		"// Copyright 2026 FINOS",
		"// SPDX-License-Identifier: Apache-2.0",
		"// Generated by `mck kit sync`; do not edit. See kit.lock.json.",
		`export const EMBEDDED_KIT_COMMIT = ${JSON.stringify(commit)};`,
		"export const EMBEDDED_KIT: ReadonlyMap<string, string> = new Map<string, string>([",
		...entries,
		"]);",
		"",
	].join("\n");
}

export function writeSnapshot(packageRoot: string, files: ReadonlyMap<string, Uint8Array>, commit: string): void {
	const kitDirectory = path.join(packageRoot, "kit");
	rmSync(kitDirectory, { force: true, recursive: true });
	for (const [key, bytes] of files) {
		const target = path.join(kitDirectory, ...key.split("/"));
		mkdirSync(path.dirname(target), { recursive: true });
		writeFileSync(target, bytes);
	}
	writeFileSync(path.join(kitDirectory, EMBEDDED), embeddedModule(files, commit));
}

export interface SyncOptions {
	readonly force: boolean;
	readonly now?: Date;
}

export async function syncKit(packageRoot: string, repositoryRoot: string, options: SyncOptions): Promise<KitLock> {
	const commit = git(repositoryRoot, "rev-parse", "HEAD");
	let previous: KitLock | null = null;
	try {
		previous = readLock(packageRoot);
	} catch {
		previous = null;
	}
	if (previous !== null && previous.commit !== commit && !options.force) {
		let isAncestor = false;
		try {
			execFileSync("git", ["merge-base", "--is-ancestor", commit, previous.commit], { cwd: repositoryRoot, stdio: "ignore" });
			isAncestor = true;
		} catch {
			isAncestor = false;
		}
		if (isAncestor) throw new Error(`${commit} is older than the pinned commit ${previous.commit}; pass --force to move backwards`);
	}
	const files = await collectSnapshot(repositoryRoot);
	writeSnapshot(packageRoot, files, commit);
	const lock: KitLock = {
		repository: REPOSITORY,
		path: KIT_PATH,
		commit,
		contentHash: contentHash(files),
		syncedAt: (options.now ?? new Date()).toISOString().slice(0, 10),
	};
	writeLock(packageRoot, lock);
	return lock;
}

export interface KitStatus {
	readonly ok: boolean;
	readonly expected: string;
	readonly actual: string;
}

export function kitStatus(packageRoot: string): KitStatus {
	const lock = readLock(packageRoot);
	const actual = contentHash(snapshotOf(packageRoot));
	return { ok: actual === lock.contentHash, expected: lock.contentHash, actual };
}
